### ISSUE TITLE
styling Property view page

### ISSUE THREAD

**Issue by PetrFila** [aggressivecutie/RealEstateAgent#6]
- screening all property photos as a carousel and details
- adding map with the right position showed
- aligning all elements in the right the order and right size

**Comment by aggressivecutie** [comment]
Detailed property post should look like:
<img width="217" alt="screen shot 2017-10-19 at 3 14 17 pm" src="https://user-images.githubusercontent.com/30378662/31753995-3cc88fec-b4e0-11e7-8715-25e2d0df5d4b.png">

**Comment by biancapower** [comment]
Done
